### ISSUE TITLE
JSON.stringify doesn't make everything a string

### ISSUE THREAD

**Issue by ericclemmons** [willrstern/rules-runner#1]
[`contains.js`][1] uses `JSON.stringify` to cast things into strings, but it has unexpected results for `undefined` and strings:

```js
[null, undefined, 0, 1, true, false, Infinity, "foo", {}, []].map(JSON.stringify);
// ["null", undefined, "0", "1", "true", "false", "null", ""foo"", "{}", "[]"]
```

Perhaps you'd prefer `String` instead?

```js
[null, undefined, 0, 1, true, false, Infinity, "foo", {}, []].map(String);
// ["null", "undefined", "0", "1", "true", "false", "Infinity", "foo", "[object Object]", ""]
```

[1]: https://github.com/willrstern/rules-runner/blob/d8d8570f0422eabd67f120b654e060a649bc4032/lib/comparator/contains.js#L2

**Comment by ericclemmons** [comment]
Alternatively, if you want to make arrays & objects more useful, you can test for that:

```js
[null, undefined, 0, 1, true, false, Infinity, "foo", {}, []].map(function(test) {
  return typeof test === "object" ? JSON.stringify(test) : String(test);
});
// ["null", "undefined", "0", "1", "true", "false", "Infinity", "foo", "{}", "[]"]
```

**Comment by willrstern** [comment]
Got it with https://github.com/willrstern/rules-runner/commit/d2f0ba4a4c704898f3bc2ba59e066e9c2414b2a4
