### ISSUE TITLE
change syntax to "when" "then" "otherwise" instead of "if" "else"

### ISSUE THREAD

**Issue by willrstern** [willrstern/rules-runner#3]

**Comment by willrstern** [comment]
@willrstern

**Comment by newgeekorder** [comment]
is the "else" option deliberately not included ?

**Comment by willrstern** [comment]
It just needs to be added.  This was originally a port of the `if/then` functionality of https://github.com/CodeMeme/RulesBundle
With plans to get `else` in there.

I'll try to get it in there today.

**Comment by willrstern** [comment]
addressed in https://github.com/willrstern/rules-runner/pull/8
